/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Io.Gate.GateApi.Client.OpenAPIDateConverter;

namespace Io.Gate.GateApi.Model
{
    /// <summary>
    /// FindCoin
    /// </summary>
    [DataContract]
    public partial class FindCoin :  IEquatable<FindCoin>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindCoin" /> class.
        /// </summary>
        /// <param name="cointype">Currency type: swap - voucher; lock - locked position; debt - US Treasury bond..</param>
        public FindCoin(string cointype = default(string))
        {
            this.Cointype = cointype;
        }

        /// <summary>
        /// Currency type: swap - voucher; lock - locked position; debt - US Treasury bond.
        /// </summary>
        /// <value>Currency type: swap - voucher; lock - locked position; debt - US Treasury bond.</value>
        [DataMember(Name="cointype")]
        public string Cointype { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FindCoin {\n");
            sb.Append("  Cointype: ").Append(Cointype).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FindCoin);
        }

        /// <summary>
        /// Returns true if FindCoin instances are equal
        /// </summary>
        /// <param name="input">Instance of FindCoin to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FindCoin input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Cointype == input.Cointype ||
                    (this.Cointype != null &&
                    this.Cointype.Equals(input.Cointype))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cointype != null)
                    hashCode = hashCode * 59 + this.Cointype.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
